{
 "title": "Grafana netology",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "FS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{fstype=\"ext4\"}"
    }
   ]
  },
  {
   "title": "CPU%",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by(instance)(rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) * 100"
    }
   ]
  },
  {
   "title": "MemFree",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemFree_bytes\r", "legendFormat": "Use" },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "All" }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg\r" },
    { "expr": "\r\navg\r" },
    {
     "expr": "\r\navg by (instance)(rate(node_load15{}[$__rate_interval]))"
    }
   ]
  }
 ]
}