apiVersion: v1
kind: Service
metadata:
  name: my-service-nodeport
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - name: http-nginx
      port: 80
      targetPort: 80
      nodePort: 30001
    - name: http-multitool
      port: 8080
      targetPort: 8080
      nodePort: 30002
